name = "cert-warning-list-proxy"
main = "src/worker.js"
compatibility_date = "2025-05-24"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "cert.cyberkatalog.pl", custom_domain = true },
]
